DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS GENRE;
CREATE TABLE AUTHOR(ID BIGSERIAL PRIMARY KEY NOT NULL, NAME VARCHAR(255));
CREATE TABLE GENRE(ID BIGSERIAL PRIMARY KEY NOT NULL, NAME VARCHAR(255));
CREATE TABLE BOOK(ID BIGSERIAL PRIMARY KEY NOT NULL, NAME VARCHAR(255), AUTHOR_ID BIGINT, GENRE_ID BIGINT, FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID), FOREIGN KEY (GENRE_ID) REFERENCES GENRE(ID));
